// <auto-generated />
using AspNet5SQLite.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AspNetCoreSQLite.Migrations.KingsAwardDataBaseMigrations
{
    [DbContext(typeof(KingsAwardDataBase))]
    [Migration("20180513033736_testMigration")]
    partial class testMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("AspNetCoreSQLite.Model.Child", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("Created");

                    b.Property<string>("DOB");

                    b.Property<byte[]>("Data");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<short>("Gender");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.Property<string>("Nick");

                    b.Property<int>("Year");

                    b.HasKey("id");

                    b.ToTable("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
